# name: Deploy GitHub Pages

# # 触发条件：在 push 到 mian 分支后
# on:
#   push:
#     branches:
#       - main

# # 任务
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: false

#       - uses: actions/setup-node@v2
#         with:
#           node-version: 16
          
#       - name: Build
#         run: npm install && npm run build

#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         with:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           BRANCH: gh-pages
#           FOLDER: public




name: Build and Deploy
# 监听 master 分支上的 push 事件
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    # 构建环境使用 ubuntu
    runs-on: ubuntu-latest
    steps:
      # 官方action, 将代码拉取到虚拟机
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 安装node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"

      # 下载依赖、打包项目
      - name: Install and Build
        run: |
          yarn install
          yarn build

      # 部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          # 项目配置的打包目录名称
          folder: public
          # 提交分支名
          branch: gh-pages
